import { Indicador } from '../types/kpi';

export function createSampleKPI(): Indicador[] {
  const kpis: Indicador[] = [
    {
      id: 'KPI001',
      codigo: 'IND-COM-001',
      nome: 'Taxa de Satisfação do Cliente',
      departamento: 'Comercial',
      processoId: 'proc-001',
      processoNome: 'Atendimento ao Cliente',
      responsavel: 'Maria Silva',
      unidadeMedida: '%',
      periodicidade: 'Mensal',
      tipoConsolidacao: 'Média',
      formulaCalculo: '(Total de clientes satisfeitos / Total de clientes pesquisados) x 100',
      fonteDados: 'Sistema CRM - Pesquisas de Satisfação',
      tipoIndicador: 'Estratégico',
      meta: 90,
      limiteMinimo: 85,
      limiteMaximo: 95,
      tendencia: 'Crescente',
      resultadoAtual: 92,
      resultadoAcumulado: 91.5,
      historicoResultados: [
        { mes: 1, ano: 2026, valor: 88 },
        { mes: 2, ano: 2026, valor: 92, observacao: 'Melhoria após implementação de novo protocolo' },
        { mes: 11, ano: 2025, valor: 87 },
        { mes: 12, ano: 2025, valor: 89 },
      ],
      analiseCritica: 'O indicador está dentro da meta estabelecida. A implementação do novo protocolo de atendimento em fevereiro resultou em aumento de 4 pontos percentuais.',
      observacoes: 'Manter monitoramento constante e reforçar treinamentos.',
      dataCriacao: '2026-01-10T10:00:00.000Z',
      dataUltimaAtualizacao: new Date().toISOString(),
      ativo: true,
    },
    {
      id: 'KPI002',
      codigo: 'IND-PROD-001',
      nome: 'Índice de Produtividade',
      departamento: 'Produção',
      responsavel: 'João Santos',
      unidadeMedida: 'unidades/hora',
      periodicidade: 'Mensal',
      tipoConsolidacao: 'Média',
      formulaCalculo: 'Total de unidades produzidas / Total de horas trabalhadas',
      fonteDados: 'Sistema MES',
      tipoIndicador: 'Operacional',
      meta: 150,
      tendencia: 'Crescente',
      resultadoAtual: 142,
      resultadoAcumulado: 145,
      historicoResultados: [
        { mes: 1, ano: 2026, valor: 148 },
        { mes: 2, ano: 2026, valor: 142, observacao: 'Redução devido a manutenção preventiva' },
        { mes: 11, ano: 2025, valor: 145 },
        { mes: 12, ano: 2025, valor: 147 },
      ],
      analiseCritica: 'Indicador em atenção devido à manutenção preventiva realizada em fevereiro. Previsão de retorno aos níveis normais em março.',
      dataCriacao: '2026-01-10T10:00:00.000Z',
      dataUltimaAtualizacao: new Date().toISOString(),
      ativo: true,
    },
    {
      id: 'KPI003',
      codigo: 'IND-FIN-001',
      nome: 'Faturamento Mensal',
      departamento: 'Financeiro',
      responsavel: 'Carlos Oliveira',
      unidadeMedida: 'R$',
      periodicidade: 'Mensal',
      tipoConsolidacao: 'Somatório',
      formulaCalculo: 'Soma de todas as notas fiscais emitidas no período',
      fonteDados: 'Sistema ERP - Módulo Financeiro',
      tipoIndicador: 'Estratégico',
      meta: 500000,
      tendencia: 'Crescente',
      resultadoAtual: 520000,
      resultadoAcumulado: 1010000,
      historicoResultados: [
        { mes: 1, ano: 2026, valor: 490000 },
        { mes: 2, ano: 2026, valor: 520000 },
        { mes: 11, ano: 2025, valor: 480000 },
        { mes: 12, ano: 2025, valor: 510000 },
      ],
      analiseCritica: 'Meta superada em 4%. Crescimento impulsionado por novos contratos fechados em janeiro.',
      dataCriacao: '2026-01-10T10:00:00.000Z',
      dataUltimaAtualizacao: new Date().toISOString(),
      ativo: true,
    },
    {
      id: 'KPI004',
      codigo: 'IND-QUAL-001',
      nome: 'Taxa de Não Conformidades',
      departamento: 'Qualidade',
      responsavel: 'Ana Paula',
      unidadeMedida: '%',
      periodicidade: 'Mensal',
      tipoConsolidacao: 'Média',
      formulaCalculo: '(Total de produtos não conformes / Total de produtos inspecionados) x 100',
      fonteDados: 'Sistema de Qualidade',
      tipoIndicador: 'Tático',
      meta: 2,
      tendencia: 'Decrescente',
      resultadoAtual: 3.5,
      resultadoAcumulado: 3.2,
      historicoResultados: [
        { mes: 1, ano: 2026, valor: 2.9 },
        { mes: 2, ano: 2026, valor: 3.5, observacao: 'Aumento devido a lote com problema de matéria-prima' },
        { mes: 11, ano: 2025, valor: 1.8 },
        { mes: 12, ano: 2025, valor: 2.1 },
      ],
      analiseCritica: 'Indicador fora da meta. Identificado problema no lote LP-2026-045 de matéria-prima. Fornecedor já notificado e plano de ação em andamento.',
      observacoes: 'Reforçar inspeção de recebimento de matéria-prima.',
      dataCriacao: '2026-01-10T10:00:00.000Z',
      dataUltimaAtualizacao: new Date().toISOString(),
      ativo: true,
    },
    {
      id: 'KPI005',
      codigo: 'IND-RH-001',
      nome: 'Taxa de Turnover',
      departamento: 'Recursos Humanos',
      responsavel: 'Patricia Costa',
      unidadeMedida: '%',
      periodicidade: 'Mensal',
      tipoConsolidacao: 'Média',
      formulaCalculo: '((Admissões + Desligamentos) / 2) / Total de colaboradores x 100',
      fonteDados: 'Sistema de RH',
      tipoIndicador: 'Estratégico',
      meta: 3,
      limiteMinimo: 2,
      limiteMaximo: 4,
      tendencia: 'Estável',
      resultadoAtual: 2.8,
      resultadoAcumulado: 2.9,
      historicoResultados: [
        { mes: 1, ano: 2026, valor: 3.0 },
        { mes: 2, ano: 2026, valor: 2.8 },
        { mes: 11, ano: 2025, valor: 2.9 },
        { mes: 12, ano: 2025, valor: 3.1 },
      ],
      analiseCritica: 'Indicador dentro da faixa aceitável. Mantido estável nos últimos meses.',
      dataCriacao: '2026-01-10T10:00:00.000Z',
      dataUltimaAtualizacao: new Date().toISOString(),
      ativo: true,
    },
    {
      id: 'KPI006',
      codigo: 'IND-LOG-001',
      nome: 'Prazo Médio de Entrega',
      departamento: 'Logística',
      responsavel: 'Roberto Lima',
      unidadeMedida: 'dias',
      periodicidade: 'Mensal',
      tipoConsolidacao: 'Média',
      formulaCalculo: 'Média dos prazos de entrega de todos os pedidos do período',
      fonteDados: 'Sistema de Logística',
      tipoIndicador: 'Operacional',
      meta: 5,
      tendencia: 'Decrescente',
      resultadoAtual: 4.2,
      resultadoAcumulado: 4.5,
      historicoResultados: [
        { mes: 1, ano: 2026, valor: 4.8 },
        { mes: 2, ano: 2026, valor: 4.2 },
        { mes: 11, ano: 2025, valor: 5.1 },
        { mes: 12, ano: 2025, valor: 4.9 },
      ],
      analiseCritica: 'Indicador dentro da meta. Melhoria contínua nos processos logísticos.',
      dataCriacao: '2026-01-10T10:00:00.000Z',
      dataUltimaAtualizacao: new Date().toISOString(),
      ativo: true,
    },
  ];

  return kpis;
}

// Tornar função global para uso no console
if (typeof window !== 'undefined') {
  (window as any).createSampleKPI = createSampleKPI;
}